### PR TITLE
Bugfix: editing current period

### LINKED ISSUE #155: Editinig current period
Description of the error:

1. Updating the storage: uncomment ```_todayPeriod(6).catch((err) => console.error(err));``` The application looks like this:

Image

2. Click on the ```Mark``` button.  After this the application will look like this:

Image

3. Edit the marked days like this:

Image

4. Click on the ```Save``` button. The result will be like this:

Image

It is necessary to redo the calculations taking into account this situation.

### PR DESCRIPTION
**Pull request by IraSoro**
Closed #155 

The bug is described in the issue. I fixed it. Now if you follow all the steps described in the problem, an alert will appear with a warning. And also the marked days will become as before editing.
image

### CODE REVIEW

File: src/state/CalculationLogics.ts [hunk 1]
```diff
@@ -409,3 +409,30 @@ export function isPeriodToday(cycles: Cycle[]) {
...
   return dayOfCycle <= cycles[0].periodLength;
 }
+
+export function isMarkedFutureDays(periodDays: string[]) {
+  if (periodDays.length === 0) {
+    return false;
+  }
+
+  periodDays.sort((left, right) => {
+    const leftDate = new Date(left);
```
Comment (imblowfish) [inline src/state/CalculationLogics.ts:419]: Please use startOfToday from date fns instead

File: src/pages/TabHome.tsx [hunk 2]
```diff
@@ -238,7 +240,16 @@ const TabHome = (props: HomeProps) => {
                           return parseISO(isoDateString).toString();
                         });
 
-                        updateCycles(getNewCyclesHistory(periodDaysString));
+                        if (!isMarkedFutureDays(periodDaysString)) {
```
Comment (imblowfish) [inline src/pages/TabHome.tsx:243]: if (isMarkedFutureDays(...)) {
 .. 
 return;
}
update..

File: src/state/CalculationLogics.ts [hunk 3]
```diff
@@ -409,3 +409,30 @@ export function isPeriodToday(cycles: Cycle[]) {
...
+
+  const today = startOfToday();
+
+  if (periodDays.includes(today.toString())) {
+    return false;
+  }
+
+  if (
+    periodDays.find((date) => {
+      return new Date(date) > today;
```
Comment (imblowfish) [inline src/state/CalculationLogics.ts:432]: Date fns

File: src/state/CalculationLogics.ts [hunk 4]
```diff
@@ -409,3 +409,30 @@ export function isPeriodToday(cycles: Cycle[]) {
...
+  });
+
+  const today = startOfToday();
+
+  if (periodDays.includes(today.toString())) {
+    return false;
+  }
+
+  if (
+    periodDays.find((date) => {
```
Comment (imblowfish) [inline src/state/CalculationLogics.ts:431]: Dont use if else and just return expression result

**Review by imblowfish — CHANGES_REQUESTED** [review]
I have one question. What if user marked one of the days in the previous period by error. Is it still available to remove unnecessary day or this these changes are persistent?

File: src/state/CalculationLogics.ts [hunk 5]
```diff
@@ -409,3 +409,30 @@ export function isPeriodToday(cycles: Cycle[]) {
 
   return dayOfCycle <= cycles[0].periodLength;
 }
+
+export function isMarkedFutureDays(periodDays: string[]) {
+  if (periodDays.length === 0) {
```
Comment (imblowfish) [inline src/state/CalculationLogics.ts:414]: You dont need this check because if period Days is empty then `includes` check below will not pass

File: src/pages/TabHome.tsx [hunk 6]
```diff
@@ -83,6 +84,7 @@ const TabHome = (props: HomeProps) => {
   const [isInfoModal, setIsInfoModal] = useState(false);
   const [isWelcomeModal, setIsWelcomeModal] = useState(false);
   const [periodTodayAlert] = useIonAlert();
+  const [noSaveAlert] = useIonAlert();
```
Comment (imblowfish) [inline src/pages/TabHome.tsx:87]: `cannotSaveAlert` look better in my opinion

File: src/state/CalculationLogics.ts (hunk 5 above)
Comment (IraSoro) [reply src/state/CalculationLogics.ts:414]: Removed

File: src/state/CalculationLogics.ts (hunk 1 above)
Comment (IraSoro) [reply src/state/CalculationLogics.ts:419]: Fixed

File: src/state/CalculationLogics.ts [hunk 7]
```diff
@@ -409,3 +409,30 @@ export function isPeriodToday(cycles: Cycle[]) {
...
+    return false;
+  }
+
+  periodDays.sort((left, right) => {
+    const leftDate = new Date(left);
+    const rightDate = new Date(right);
+    return leftDate.getTime() - rightDate.getTime();
```
[the remark this answers is not in the document]
Comment (IraSoro) [reply src/state/CalculationLogics.ts:421]: Fixed

File: src/state/CalculationLogics.ts (hunk 3 above)
Comment (IraSoro) [reply src/state/CalculationLogics.ts:432]: Fixed

File: src/state/CalculationLogics.ts (hunk 4 above)
Comment (IraSoro) [reply src/state/CalculationLogics.ts:431]: fixed

File: src/pages/TabHome.tsx (hunk 6 above)
Comment (IraSoro) [reply src/pages/TabHome.tsx:87]: Renamed

File: src/pages/TabHome.tsx (hunk 2 above)
Comment (IraSoro) [reply src/pages/TabHome.tsx:243]: Fixed

**Comment by IraSoro** [comment]
If I understood the question correctly, there will be no error. This checks if the dates following today are marked. If yes and the date is not marked today, then there is an error. Previous dates are not checked

**Review by imblowfish — APPROVED** [review]
