### PR TITLE
Fixed day shifts when marking in Welcome Modal or Tab Home

### LINKED ISSUE #143: File Format
How does the file format work? I just discovered the app and was trying to enter it all in manually, but the dates are shifted by one day or all off all together. Also, is the cycleLength specifying the number of days from the period start to the day before the next period? I am also curious how the first one is calculated.

### PR DESCRIPTION
**Pull request by imblowfish**
Closes #143

The problem occured if the user's timezone differed from the UTC timezone by 1 day. In this case, ISO string was passed as parameter to IonDatetime's `isDateEnabled` or `highlightedDates`. And inside these functions the date was passed to `Date` constructor. The `Date` constructor in turn, translated this date into local time, which could case a shift.

As example. Now is October 28 01:15 in UTC. Let's imagine that user has `America/Los_Angeles` timezone.  IonDatetime passes ISO string `2023-10-28` as parameter for `isDateEnabled` callback. This string is passed as argument in the `Date` constructor and `Date` returns `Fri Oct 27 2023 17:00:00 GMT-0700 (Pacific Daylight Time)` to us. But initially the date is already described the current day from IonDatetime and we don't need to re-convert the time to the current timezone.

To get rid of this convertion I changed `Date` constructor to `parseISO` function from `date-fns`.

Also I changed this behavior in `CalculationsLogic.ts`. I tried to implement unit tests, but didn't found any possibility to change timezone in a specific tests wich Jest like we can do that in the Chrome Devtools with `Sensors`, so I added a new tests in the test plan.

### CODE REVIEW

File: src/pages/TabHome.tsx [hunk 1]
```diff
@@ -199,12 +200,12 @@ const TabHome = (props: HomeProps) => {
                 isDateEnabled={(date: string) => {
```
Comment (IraSoro) [inline src/pages/TabHome.tsx:200]: I suggest parsing here so that in ```getActiveDates``` there are only calculations.
And change  ```date: string``` argument to ```isoDateString```.

File: src/state/CalculationLogics.ts [hunk 2]
```diff
@@ -301,8 +307,8 @@ export function getLastPeriodDays(cycles: Cycle[]) {
   return periodDays;
 }
 
-export function getActiveDates(dateString: string, cycles: Cycle[]) {
-  const date = startOfDay(new Date(dateString));
+export function getActiveDates(isoDateString: string, cycles: Cycle[]) {
+  const date = startOfDay(parseISO(isoDateString));
```
Comment (IraSoro) [inline src/state/CalculationLogics.ts:311]: Therefore, remove the ```parseISO``` here

**Comment by IraSoro** [comment]
There are more sensory tests, so I will replace them into issues in the new milestone “Tests”.

**Comment by IraSoro** [comment]
I found some bugs:
1. Array of cycles is empty. Welcome modal is open. I mark period days:
image

2. I click the ```continue``` button. Home tab is open. Calendar looks like this:
image

3. But if we want to see future days of period, it will not show one day (there should be 5 marked and not 4)
image

**Comment by IraSoro** [comment]
2. This bug follows from the first one

1. Open ```Welcome modal```. Mark this days:
image

2.  Here you can see that your period is today, but today is not marked
image

From these two bugs it turns out that the app doesn`t count the future first day of period

**Comment by IraSoro** [comment]
But if the array is full (the fuction ```_todayPeriod(6).catch((err) => console.error(err));``` is uncommented), it calculates everything correctly
image

**Comment by IraSoro** [comment]
You can also delete the `TEST_PLAN.md` file. I created a new [milestone](https://github.com/IraSoro/peri/milestone/13) and moved all the described tests there.

**Comment by imblowfish** [comment]
> I found some bugs: 1.
> 
> 1. Array of cycles is empty. Welcome modal is open. I mark period days:
>    image
> 2. I click the `continue` button. Home tab is open. Calendar looks like this:
>    image
> 3. But if we want to see future days of period, it will not show one day (there should be 5 marked and not 4)
>    image

Fixed

**Tested with San Francisco**
image
image
image
image

**Tested with Tokyo**
image
image
image
image

File: src/pages/TabHome.tsx (hunk 1 above)
Comment (imblowfish) [reply src/pages/TabHome.tsx]: Agree, fixed

File: src/state/CalculationLogics.ts (hunk 2 above)
Comment (imblowfish) [reply src/state/CalculationLogics.ts]: Fixed

**Comment by imblowfish** [comment]
I fixed all problems described above and added related tests
Also, in this PR I changed cycles storage approach. Previously we stored cycle start date as "yyyy-MM-dd", but not we'll store it as local date instead

**Comment by IraSoro** [comment]
I found a bug.
Steps:
1. Set San Francisco location
2. Set empty array
3. Open `Welcome modal` and mark these days:
image

4. Click `continue` and move to the `tab Home`:
image

5. Click `mark button`
image

There was a shift back 1 day. This only happens in the San Francisco location. 

And the array can be made not empty. You can, for example, uncomment the `_randomLutealPhase(6)` function (or `_randomDelayOfCycle(6) or _todayPeriod(6));` function):
image

Then after clicking the `Mark button` the shift back will still be:
image

**Review by IraSoro — CHANGES_REQUESTED** [review]
I found a bug.
Steps:
1. Set San Francisco location
2. Set empty array
3. Open `Welcome modal` and mark these days:
image

4. Click `continue` and move to the `tab Home`:
image

5. Click `mark button`
image

There was a shift back 1 day. This only happens in the San Francisco location. 

And the array can be made not empty. You can, for example, uncomment the `_randomLutealPhase(6)` function (or `_randomDelayOfCycle(6) or _todayPeriod(6));` function):
image

Then after clicking the `Mark button` the shift back will still be:
image

**Review by IraSoro — APPROVED** [review]
I didn't find any bugs
